services:
  maestro-backend:
    build: .
    container_name: maestro-backend
    networks:
      - maestro-network
    ports:
      - "3000:3000"
    restart: always
    environment:
      - UPLOAD_DIR=/data/attachments
    volumes:
      - /opt/applicationStorage/orquestra/attachments/projects:/data/attachments

networks:
  maestro-network:
    external: true